"""Public API for synth_head.core."""

from .math import clamp, euler_degrees_to_quaternion, quaternion_to_euler_degrees
from .constraints import (
    ConstraintRules,
    ValidationReport,
    constrain,
    expand_joint_keys,
    flatten_params,
    load_rules,
    unflatten_params,
    validate_rules,
)
from .modifiers import SmoothCorrectiveConfig
from .variation import (
    CHAOS_JOINT_NAMES,
    DEFAULT_JOINT_OVERRIDES,
    ChaosTransform,
    VariationConfig,
    classify_joints,
    generate_chaos_transforms,
    generate_single_frame_transforms,
)
from .snapshot import build_snapshot, save_snapshot, load_snapshot
from .blendshapes import (
    VARIATION_SHAPES,
    EXPRESSION_SHAPES,
    DEFAULT_VARIATION_OVERRIDES,
    DEFAULT_EXPRESSION_OVERRIDES,
    BlendshapeConfig,
    classify_variation_shapes,
    classify_expression_shapes,
    generate_blendshape_weights,
    generate_single_frame_blendshape_weights,
)
from .config import RunnerConfig, PipelineConfig, BakeSettings, load_config
from .rerandomize import (
    RerandomizeConfig,
    ResolvedTarget,
    resolve_targets,
    rerandomize_flat,
    sample_value,
    build_param_registry,
)
from .attractor import (
    AttractorConfig,
    PoolCache,
    get_pool_cache,
    attract,
    update_manifest,
    snapshot_to_flat,
)
from .texture_swap import (
    TextureSwapSlot,
    TextureSwapConfig,
    SequenceManifest,
    load_manifest,
    rebuild_sequence,
    ping_and_sync_sequence,
    pick_texture_index,
    calc_offset,
    name_from_current_offset,
    offset_from_name,
    sequence_prefix,
    sequence_filename,
)

__all__ = [
    "clamp",
    "euler_degrees_to_quaternion",
    "quaternion_to_euler_degrees",
    "ConstraintRules",
    "ValidationReport",
    "constrain",
    "expand_joint_keys",
    "flatten_params",
    "load_rules",
    "unflatten_params",
    "validate_rules",
    "SmoothCorrectiveConfig",
    "CHAOS_JOINT_NAMES",
    "DEFAULT_JOINT_OVERRIDES",
    "ChaosTransform",
    "VariationConfig",
    "classify_joints",
    "generate_chaos_transforms",
    "generate_single_frame_transforms",
    "VARIATION_SHAPES",
    "EXPRESSION_SHAPES",
    "DEFAULT_VARIATION_OVERRIDES",
    "DEFAULT_EXPRESSION_OVERRIDES",
    "BlendshapeConfig",
    "classify_variation_shapes",
    "classify_expression_shapes",
    "generate_blendshape_weights",
    "generate_single_frame_blendshape_weights",
    "build_snapshot",
    "save_snapshot",
    "load_snapshot",
    "RunnerConfig",
    "PipelineConfig",
    "BakeSettings",
    "load_config",
    "RerandomizeConfig",
    "ResolvedTarget",
    "resolve_targets",
    "rerandomize_flat",
    "sample_value",
    "build_param_registry",
    "AttractorConfig",
    "PoolCache",
    "get_pool_cache",
    "attract",
    "update_manifest",
    "snapshot_to_flat",
    "TextureSwapSlot",
    "TextureSwapConfig",
    "SequenceManifest",
    "load_manifest",
    "rebuild_sequence",
    "ping_and_sync_sequence",
    "pick_texture_index",
    "calc_offset",
    "name_from_current_offset",
    "offset_from_name",
    "sequence_prefix",
    "sequence_filename",
]
